import Head from "next/head"
import Image from "next/image"

export default function Create() {
  return (
    <>
      <Head>
        <title>Invoice Maker | Create</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <h1>Fill in the form to create an invoice</h1>
        <article>
          <Address />
        </article>
      </section>
    </>
  )
}

const Address = () => {
  return (
    <>
      <form className="invoice-form">
        <div className="formControl">
          <label htmlFor="companyname">Your Company Name : </label>
          <input type="text" id="companyname" name="companyname" />
        </div>
        <div className="formControl">
          <label htmlFor="firstline">First Line : </label>
          <input type="text" id="firstline" name="firstline" />
        </div>
        <div className="formControl">
          <label htmlFor="secondline">Second Line : </label>
          <input type="text" id="secondline" name="secondline" />
        </div>
        <div className="formControl">
          <label htmlFor="city">City :</label>
          <input type="text" id="city" name="city" />
        </div>
        <div className="formControl">
          <label htmlFor="postcode">Postcode :</label>
          <input type="text" id="postcode" name="postcode" />
        </div>
      </form>
    </>
  )
}
