import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo quaerat
          assumenda, quo molestiae ab non fugit esse, blanditiis a, perferendis
          voluptatem quasi ipsum quibusdam excepturi asperiores beatae odit!
          Nostrum saepe animi incidunt! Explicabo, perspiciatis. Architecto,
          alias? Maiores blanditiis tempora assumenda impedit similique,
          repellendus reiciendis dolore culpa omnis consectetur recusandae quas
          ea sequi dolores magni fugit nesciunt, sint ratione est nihil hic
          officiis esse. Est dolores nam omnis nemo? Similique magni officia
          repellat dolores, quis alias perspiciatis minus temporibus, amet
          consectetur ad omnis. Harum minima ut distinctio non alias, voluptate
          perferendis.
        </p>
      </main>
    </>
  )
}
